export const sections = [
    'Public Profile',
    'Hr Information',
    'Personal Data',
    'Payroll Information',
    'Bank Details',
    'Emergency Contact',
    'Employee Equipment',
    'Development',
];

export const employeeProfileBlank = {
    public: {
        firstName: '',
        lastName: '',
        gender: '',
        email: '',
        companyPhoneNumb: '',
        office: '',
        department: '',
        position: '',
        team: '',
        linkedIn: '',
        birthday: '',
        phoneNumber: '',
    },

    hrInformation: {
        status: '',
        employmentType: '',
        occupationType: '',
        supervisor: '',
        hireDate: '',
        contractEnd: '',
        lengthOfProbation: '',
        noticePeriod: '',
        weeklyHours: '',
        costCenter: '',
        nationality: '',
        residentPermitValidUntil: '',
    },

    personalData: {
        streetAndHouseNumber: '',
        postalCode: '',
        city: '',
        privateEmail: '',
        privatePhone: '',
    },

    payrollInformation: {
        salaryType: '',
        taxID: '',
        socialSecurityNumber: '',
        wageTaxClass: '',
        children: '',
        childAllowance: '',
        maritalStatus: '',
        religiousDenomination: '',
        typeOfHealthInsurance: '',
        nameOfHealthInsurance: '',
        mainOrSecondaryOccupation: '',
        wagetaxAllowance: '',
    },

    bankDetails: {
        holderOfBankAccount: '',
        iban: '',
        bic: '',
    },

    emergencyContact: {
        name: '',
        phoneNumber: '',
    },

    employeeEquipment: {
        notebook: '',
        cellPhone: '',
    },

    development: {
        training: '',
    },
};

export const team = [
    'Test Automation',
    'Backend',
    'Frontend',
    'BIZ',
    'OPS',
    'HR',
    'Management',
    'PAM',
    'Finance',
    'Content & Communication',
    'Test Experts',
    'empty',
];

export const department = ['Delivery', 'HR', 'Management', 'Platform', 'Sales', 'Finance', 'OPS', 'empty'];

export const office = [
    'Würzburg(Germany)',
    'Accra (Ghana)',
    'Sagamu (Nigeria)',
    'Yaounde(Cameroun)',
    'Cologne (Germany)',
    'Lagos(Nigeria)',
    'Munich(Germany)',
    'Khartoum (Sudan)',
    'Remote',
    'Istantbul(Turkey)',
    'Berlin (Germany)',
    'Frankfurt (Germany)',
    'Ahlden (Germany)',
    'Nürnberg (Germany)',
    'Beirut (Lebanon)',
    'Stutgart (Germany)',
];

export const positions = [
    'Working Student Software Developer',
    'Working Student Presales',
    'Working Student Junior Software Developer',
    'Working Student  Javascript',
    'Working Student  Frontend Developer',
    'Working Student  Business Analyst',
    'Working Student Software Testing',
    'Technical Writer',
    'Software Testing',
    'Software Developer',
    'Software Architect',
    'Social Media Coordinator',
    'Senior System Engineer',
    'Senior Software Developer',
    'Senior Jakarta EE Developer',
    'Senior Frontend Developer',
    'Senior Consultatn (Claims Expert)',
    'Senior Business Analyst',
    'Senior Business Analyst/Product Owner',
    'Quality Manager',
    'Project Manager/ Business Analyst',
    'Project Manager/ Agile Coach Testing',
    'Management Consultant',
    'Junior Tester',
    'Junior Software Tester',
    'Junior Software Developer',
    'Junior Software Developer Java',
    'Junior Software Developer (Frontend)',
    'Junior Scrum Master',
    'Junior HR Manager',
    'Junior Devops Engineer',
    'Junior Business Analyst',
    'Intern',
    'Human Ressources Manager',
    'Database Administrator',
    'Community & Content Manager',
    'Cloud Native Java Developer',
    'Cleaning Staff',
];
